import type { Metadata } from 'next'
import { Inter, Roboto, Lobster } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components'
import { Toaster } from "react-hot-toast";
import RegisterModal from '@/components/modals/RegisterModal';
import LoginModal from '@/components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import PostBookModal from '@/components/modals/PostBookModal';
import ReduxProvider from '@/provider/ReduxProvider';

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ["100", '300', '400', '500'] })
export const lobster = Lobster({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReduxProvider>
          <RegisterModal />
          <LoginModal />
          <PostBookModal />
          <Navbar currentUser={currentUser} />
          <Toaster />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
